// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $admin_blog_action_ from "./routes/admin/blog/[action].tsx";
import * as $admin_blog_create from "./routes/admin/blog/create.tsx";
import * as $admin_blog_index from "./routes/admin/blog/index.tsx";
import * as $api_admin_blog_posts_slug_ from "./routes/api/admin/blog/posts/[slug].ts";
import * as $api_admin_blog_posts_index from "./routes/api/admin/blog/posts/index.ts";
import * as $api_auth_check from "./routes/api/auth/check.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_login from "./routes/api/login.ts";
import * as $api_register from "./routes/api/register.ts";
import * as $api_upload from "./routes/api/upload.ts";
import * as $blog_slug_ from "./routes/blog/[slug].tsx";
import * as $blog_index from "./routes/blog/index.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $login_index from "./routes/login/index.tsx";
import * as $logout from "./routes/logout.ts";
import * as $profile_index from "./routes/profile/index.tsx";
import * as $register_index from "./routes/register/index.tsx";
import * as $BlogForm from "./islands/BlogForm.tsx";
import * as $ClientsCarousel from "./islands/ClientsCarousel.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $LoginForm from "./islands/LoginForm.tsx";
import * as $Navbar from "./islands/Navbar.tsx";
import * as $RegisterForm from "./islands/RegisterForm.tsx";
import * as $RichTextEditor from "./islands/RichTextEditor.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/admin/blog/[action].tsx": $admin_blog_action_,
    "./routes/admin/blog/create.tsx": $admin_blog_create,
    "./routes/admin/blog/index.tsx": $admin_blog_index,
    "./routes/api/admin/blog/posts/[slug].ts": $api_admin_blog_posts_slug_,
    "./routes/api/admin/blog/posts/index.ts": $api_admin_blog_posts_index,
    "./routes/api/auth/check.ts": $api_auth_check,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/login.ts": $api_login,
    "./routes/api/register.ts": $api_register,
    "./routes/api/upload.ts": $api_upload,
    "./routes/blog/[slug].tsx": $blog_slug_,
    "./routes/blog/index.tsx": $blog_index,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/login/index.tsx": $login_index,
    "./routes/logout.ts": $logout,
    "./routes/profile/index.tsx": $profile_index,
    "./routes/register/index.tsx": $register_index,
  },
  islands: {
    "./islands/BlogForm.tsx": $BlogForm,
    "./islands/ClientsCarousel.tsx": $ClientsCarousel,
    "./islands/Counter.tsx": $Counter,
    "./islands/LoginForm.tsx": $LoginForm,
    "./islands/Navbar.tsx": $Navbar,
    "./islands/RegisterForm.tsx": $RegisterForm,
    "./islands/RichTextEditor.tsx": $RichTextEditor,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
